# Generated by Django 4.0.3 on 2022-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30, verbose_name='网站名')),
                ('site_url', models.CharField(max_length=120, verbose_name='网址')),
                ('site_src', models.CharField(max_length=120, verbose_name='图标地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'site',
                'db_table': 'site',
            },
        ),
    ]
